# Site settings
title: Désagréable
email: vp@desagreable.club
url: https://desagreable.com
description: "Site officiel de la populace désagréable."

# Build settings
markdown: kramdown
permalink: pretty
